# Generated by Django 2.2.4 on 2019-10-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colour',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=None),
        ),
    ]
