# Generated by Django 2.2.4 on 2019-10-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0007_auto_20191011_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
