# Generated by Django 2.2.4 on 2019-10-14 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textileapp', '0008_auto_20191014_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colour',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='textileapp.Textile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
