# Generated by Django 2.2.4 on 2019-10-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0013_auto_20191025_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=10)),
                ('price', models.IntegerField(default=None, max_length=6)),
            ],
        ),
    ]
