# Generated by Django 2.2.4 on 2019-10-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textileapp', '0014_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coupon',
        ),
    ]
